services:

  AccountsDb:
   image: sqlserver

  pgadmin:
  
   image: dpage/pgadmin4



  accounting:
    image: ${DOCKER_REGISTRY-}accounting
    build:
      context: .
      dockerfile: src\Services\AccountMangement\accounting\Dockerfile
